### ISSUE TITLE
The extension keeps searching for the unicode

### ISSUE THREAD

**Issue by itskarudo** [zensoup/ulauncher-unicode#1]
When I search for a unicode ( e.g cat ) it keeps searching for a while without giving any results
![Screenshot from 2019-07-06 12-12-02](https://user-images.githubusercontent.com/41697719/60755444-9f46f480-9fe7-11e9-9e74-3188b5d8201a.png)

**Comment by zensoup** [comment]
Thanks for submitting an issue!
The problem was that the extension failed to create a folder for caching character icons when it first launched.

It should be fixed with 0ad36c00a888e687b4bfbf76f266f1000040b337.
